name: Terraform Apply (Dev)

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  GITHUB_ENV: "dev"
  TF_INPUT: "-input=false"
  TF_IN_AUTOMATION: "1"
  AWS_REGION: "eu-west-1"
  TF_VERSION: "1.13.5"

jobs:
  apply-dev:
    name: Apply Terraform (dev)
    runs-on: ubuntu-latest
    environment: ${{ env.GITHUB_ENV }}

    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init ${{ env.TF_INPUT }}

      - name: Terraform plan (dev)
        id: plan
        working-directory: environments/dev
        run: |
          terraform plan ${{ env.TF_INPUT }} -var-file=variables.tfvars -no-color > plan.txt

      - name: Upload Terraform plan artifact (dev)
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-dev
          path: environments/dev/plan.txt
          retention-days: 7

      - name: Publish Terraform Plan Summary
        if: always()
        working-directory: environments/dev
        run: |
          echo "## Terraform Plan (dev)" >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          head -n 500 plan.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ env.TF_INPUT }} -var-file=variables.tfvars