name: Terraform Apply (Staging)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  apply-staging:
    name: Apply Terraform (staging)
    runs-on: ubuntu-latest
    environment: staging

    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        shell: bash
        working-directory: environments/staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Dev Apply Artifact
        uses: actions/download-artifact@v4
        with:
          name: dev-apply-success
          path: ./artifacts

      - name: Fail if Dev Not Applied
        run: |
          if [ ! -f ./artifacts/.last_apply ]; then
            echo "Dev must be applied first!"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file=variables.tfvars
