name: Terraform Destroy (Staging)

on:
  workflow_dispatch:

jobs:
  destroy-staging:
    name: Destroy staging Environment
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        shell: bash
        working-directory: environments/staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -input=false -var-file=variables.tfvars -out=tfplan.destroy

      - name: Terraform Destroy
        run: terraform apply -input=false tfplan.destroy
